# .github/workflows/bot.yml
name: Daily WeChat Bot

on:
  schedule:
    - cron: '30 23 * * *'  # 每天北京时间 7:30 执行
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb libnss3 libgconf-2-4 libxi6 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2
          pip install -r requirements.txt

      - name: Install Google Chrome (v124)
        run: |
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.60-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_124.0.6367.60-1_amd64.deb

      - name: Install ChromeDriver (v124)
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.60/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GAODE_API_KEY: ${{ secrets.GAODE_API_KEY }}
          QWEATHER_API_KEY: ${{ secrets.QWEATHER_API_KEY }}
          WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}
          TIAN_API_KEY: ${{ secrets.TIAN_API_KEY }}
        run: python main.py
