name: Daily WeChat Bot

on:
  schedule:
    - cron: '30 23 * * *'  # 每天北京时间 7:30 执行（23:30 UTC）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb libnss3 libxi6 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2t64

          # 安装 Chrome 浏览器
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          # 安装匹配的 ChromeDriver
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          DRIVER_URL="https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)/chromedriver_linux64.zip"
          wget "$DRIVER_URL"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # 安装 Python 依赖
          pip install -r requirements.txt

      - name: Run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GAODE_API_KEY: ${{ secrets.GAODE_API_KEY }}
          WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}
          QWEATHER_API_KEY: ${{ secrets.QWEATHER_API_KEY }}
          TIAN_API_KEY: ${{ secrets.TIAN_API_KEY }}
        run: |
          xvfb-run python main.py
